import Head from 'next/head';
import Nav from "@/components/Nav";

export const metadata = {
  title: "Suffa Mehfil",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        {/* Add Google Analytics Script */}
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-CTH7P9Q4EX"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
        
          gtag('config', 'G-CTH7P9Q4EX');
        </script>
      </Head>
      <body>
        <div className="bg main">
          <div className="gradient" />
        </div>
        <div className="app">
          <Nav />
          {children}
        </div>
      </body>
    </html>
  );
}
