import "@/styles/global.css"
import Nav from '@/components/Nav'
import { Inter } from 'next/font/google'
// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Suffa Mehfil',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="main">
          <div className="gradient"/>
        </div>

        <div className="app">
          <Nav/>
          {children}
        </div>
  
      </body>
    </html>
  )
}
