import "@/styles/global.css";
import Nav from "@/components/Nav";
import { Analytics } from "@vercel/analytics/react";

export const metadata = {
  title: "Suffa Mehfil",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="bg main">
          <div className="gradient" />
        </div>
        <div className="app">
          <Nav />
          {children}
          <Analytics />
        </div>
      </body>
    </html>
  );
}
